
project_id = "cudftlquaydissmvqjmv"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[graphql]
enabled = true
port = 54323
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[inbucket]
enabled = true
port = 54324
smtp_port = 1025
pop3_port = 1110

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54326
site_url = "https://stckr.io"
additional_redirect_urls = ["https://cudftlquaydissmvqjmv.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
port = 54327
inspector_port = 54328

[functions.stripe-webhook]
verify_jwt = false

[functions.printful-webhook]
verify_jwt = false

[functions.admin-qr-pack-delete]
verify_jwt = true

[functions.qr-assign]
verify_jwt = false

[functions.qr-generate-v2]
verify_jwt = false

[functions.qr-resolve]
verify_jwt = false

[functions.qr-resolve-v2]
verify_jwt = false

[functions.qr-claim-v2]
verify_jwt = false

